name: ReST
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - descartes=1.1.0
  - imageio=2.9.0
  - jupyter=1.0.0
  - networkx=2.7.1
  - notebook=6.4.8
  - numba=0.55.1
  - numpy=1.21.2
  - pandas=1.4.1
  - pip=21.2.4
  - plotly=5.6.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.9.11
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - setuptools=58.0.4
  - shapely=1.7.1
  - statsmodels

  - pip:
    - anndata==0.8.0
    - alphashape==1.3.1
    - h5py==3.6.0
    - natsort==8.1.0
    - pynndescent==0.5.6
    - scanpy==1.8.2
    - sinfo==0.3.4
    - stdlib-list==0.8.0
    - tqdm==4.63.1
    - umap-learn==0.5.2
    - gseapy==0.10.8