name: ReST
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pandas=0.25.3
  - numpy=1.18.5
  - matplotlib=3.3.4
  - statsmodels=0.12.0
  - scipy=1.6.1
  - tqdm=4.56.0
  - imageio
  - alphashape
  - descartes
  - python-igraph
  - leidenalg
  - joblib
  - gseapy
  - scanpy
  - anndata
  - pip:
    - scanpy